export const BUSINESS_PROFILE = {
  name: "LOrdEnRYQuE",
  brandLine: "Advanced Digital Solution",
  description: "AI Engineering, Full-Stack Development, Premium Web Development",
  location: "Germany",
  remoteFirst: true,
  timezone: "Europe/Berlin",
  hours: {
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    opens: "09:00",
    closes: "18:00",
  },
  services: [
    "Business websites",
    "Custom web apps",
    "AI-powered business tools",
    "Automation systems",
    "MVP design and development",
    "UX/UI-focused premium digital experiences",
    "Technical consulting",
  ],
  typicalClients: [
    "Small businesses",
    "Startups",
    "Restaurants",
    "Beauty businesses",
    "Service companies",
    "Personal brands",
    "Entrepreneurs",
  ],
  faq: [
    { q: "Do you build custom websites and web applications?", a: "Yes, custom websites and web apps are core services." },
    { q: "Do you offer AI integrations and workflow automation?", a: "Yes, AI integrations and automation systems are available." },
    { q: "Can projects be delivered remotely?", a: "Yes, projects are delivered remotely for clients across regions." },
    { q: "Can you support multilingual clients?", a: "Yes, multilingual client support is available." },
    { q: "How long do projects take?", a: "Timelines vary depending on scope and technical complexity." },
    { q: "How is pricing defined?", a: "Pricing is custom and based on project requirements." },
  ],
} as const;
